<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "graphql-test": {
                        "component": "Wasi_GraphqlTest/js/graphql-test"
                    }
                }
            }
        }
    }
</script>

<div data-bind="scope: 'graphql-test'">
    <pre data-bind="text: JSON.stringify($data.result, null, 2)">
        Loading....
    </pre>
</div>